/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ControllerMusica;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author unifmkuniyoshi
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        c = new ControllerMusica(this);
    }

    public JButton getBtn_buscarA() {
        return btn_buscarA;
    }

    public void setBtn_buscarA(JButton btn_buscarA) {
        this.btn_buscarA = btn_buscarA;
    }

    public JButton getBtn_voltar() {
        return btn_voltar;
    }

    public void setBtn_voltar(JButton btn_voltar) {
        this.btn_voltar = btn_voltar;
    }

    public JLabel getLbl_buscar() {
        return lbl_buscar;
    }

    public void setLbl_buscar(JLabel lbl_buscar) {
        this.lbl_buscar = lbl_buscar;
    }

    public JLabel getLbl_buscar2() {
        return lbl_buscar2;
    }

    public void setLbl_buscar2(JLabel lbl_buscar2) {
        this.lbl_buscar2 = lbl_buscar2;
    }

    public JList<String> getLista_musicas() {
        return lista_musicas;
    }

    public void setLista_musicas(JList<String> lista_musicas) {
        this.lista_musicas = lista_musicas;
    }

    public JScrollPane getPainel_musicas() {
        return painel_musicas;
    }

    public void setPainel_musicas(JScrollPane painel_musicas) {
        this.painel_musicas = painel_musicas;
    }

    public JTextField getTxt_buscarA() {
        return txt_buscarA;
    }

    public void setTxt_buscarA(JTextField txt_buscarA) {
        this.txt_buscarA = txt_buscarA;
    }

    public JTextField getTxt_buscarG() {
        return txt_buscarG;
    }

    public void setTxt_buscarG(JTextField txt_buscarG) {
        this.txt_buscarG = txt_buscarG;
    }

    public JTextField getTxt_buscarM() {
        return txt_buscarM;
    }

    public void setTxt_buscarM(JTextField txt_buscarM) {
        this.txt_buscarM = txt_buscarM;
    }

    public JLabel getLbl_info() {
        return lbl_info;
    }

    public void setLbl_info(JLabel lbl_info) {
        this.lbl_info = lbl_info;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_buscar = new javax.swing.JLabel();
        txt_buscarM = new javax.swing.JTextField();
        btn_buscarM = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        painel_musicas = new javax.swing.JScrollPane();
        lista_musicas = new javax.swing.JList<>();
        txt_buscarA = new javax.swing.JTextField();
        txt_buscarG = new javax.swing.JTextField();
        lbl_buscar2 = new javax.swing.JLabel();
        btn_buscarA = new javax.swing.JButton();
        btn_buscarG = new javax.swing.JButton();
        lbl_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_buscar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_buscar.setText("Buscar Música");

        txt_buscarM.setForeground(new java.awt.Color(102, 102, 102));
        txt_buscarM.setText("Nome da música.");
        txt_buscarM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscarMFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscarMFocusLost(evt);
            }
        });
        txt_buscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarMActionPerformed(evt);
            }
        });

        btn_buscarM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscarM.setText("Buscar");
        btn_buscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarMActionPerformed(evt);
            }
        });

        btn_voltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        lista_musicas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_musicas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lista_musicasPropertyChange(evt);
            }
        });
        painel_musicas.setViewportView(lista_musicas);

        txt_buscarA.setForeground(new java.awt.Color(102, 102, 102));
        txt_buscarA.setText("Nome do artista.");
        txt_buscarA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscarAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscarAFocusLost(evt);
            }
        });
        txt_buscarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarAActionPerformed(evt);
            }
        });

        txt_buscarG.setForeground(new java.awt.Color(102, 102, 102));
        txt_buscarG.setText("Gênero musical.");
        txt_buscarG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscarGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscarGFocusLost(evt);
            }
        });
        txt_buscarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarGActionPerformed(evt);
            }
        });

        lbl_buscar2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_buscar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_buscar2.setText("por nome, artista ou gênero");

        btn_buscarA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscarA.setText("Buscar");
        btn_buscarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarAActionPerformed(evt);
            }
        });

        btn_buscarG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscarG.setText("Buscar");
        btn_buscarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarGActionPerformed(evt);
            }
        });

        lbl_info.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_info.setForeground(new java.awt.Color(102, 102, 102));
        lbl_info.setText("Clique duas vezes na música para mais opções.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addComponent(lbl_buscar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_voltar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_info, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_buscarG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscarG))
                            .addComponent(painel_musicas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_buscarM)
                                    .addComponent(txt_buscarA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_buscarA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_buscarM, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btn_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_buscar2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_buscarM)
                    .addComponent(btn_buscarM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscarA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscarG, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btn_buscarG, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painel_musicas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_info)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarMActionPerformed

    private void txt_buscarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarAActionPerformed

    private void txt_buscarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarGActionPerformed

    private void btn_buscarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarAActionPerformed
        // TODO add your handling code here:
        c.buscarMusica();
    }//GEN-LAST:event_btn_buscarAActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        Pagina_Usuario p = new Pagina_Usuario();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void lista_musicasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lista_musicasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_musicasPropertyChange

    private void txt_buscarMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscarMFocusGained
        // TODO add your handling code here:
        c.apagaTexto(txt_buscarM, "Nome da música.");
    }//GEN-LAST:event_txt_buscarMFocusGained

    private void txt_buscarMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscarMFocusLost
        // TODO add your handling code here:
        c.geraTexto(txt_buscarM, "Nome da música.");
    }//GEN-LAST:event_txt_buscarMFocusLost

    private void txt_buscarAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscarAFocusGained
        // TODO add your handling code here:
        c.apagaTexto(txt_buscarA, "Nome do artista.");
    }//GEN-LAST:event_txt_buscarAFocusGained

    private void txt_buscarAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscarAFocusLost
        // TODO add your handling code here:
        c.geraTexto(txt_buscarA, "Nome do artista.");
    }//GEN-LAST:event_txt_buscarAFocusLost

    private void txt_buscarGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscarGFocusGained
        // TODO add your handling code here:
        c.apagaTexto(txt_buscarG, "Gênero musical.");
    }//GEN-LAST:event_txt_buscarGFocusGained

    private void txt_buscarGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscarGFocusLost
        // TODO add your handling code here:
        c.geraTexto(txt_buscarG, "Gênero musical.");
    }//GEN-LAST:event_txt_buscarGFocusLost

    private void btn_buscarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarGActionPerformed
        // TODO add your handling code here:
        c.buscarMusica();
    }//GEN-LAST:event_btn_buscarGActionPerformed

    private void btn_buscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarMActionPerformed
        // TODO add your handling code here:
        c.buscarMusica();
    }//GEN-LAST:event_btn_buscarMActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Buscar().setVisible(true);
//            }
//        });
//    }
    private ControllerMusica c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarA;
    private javax.swing.JButton btn_buscarG;
    private javax.swing.JButton btn_buscarM;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_buscar2;
    private javax.swing.JLabel lbl_info;
    private javax.swing.JList<String> lista_musicas;
    private javax.swing.JScrollPane painel_musicas;
    private javax.swing.JTextField txt_buscarA;
    private javax.swing.JTextField txt_buscarG;
    private javax.swing.JTextField txt_buscarM;
    // End of variables declaration//GEN-END:variables
}
