/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import control.ControllerLogin;
import DAO.DAO;
import java.sql.ResultSet;

/**
 *
 * @author unifmkuniyoshi
 */
public class Pagina_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Pagina_Usuario
     */
    public Pagina_Usuario() {
        initComponents();
    }
    
    ControllerLogin c = new ControllerLogin(null);

    public JButton getBtn_history() {
        return btn_history;
    }

    public void setBtn_history(JButton btn_history) {
        this.btn_history = btn_history;
    }

    public JButton getBtn_musicas() {
        return btn_musicas;
    }

    public void setBtn_musicas(JButton btn_musicas) {
        this.btn_musicas = btn_musicas;
    }

    public JButton getBtn_playlists() {
        return btn_playlists;
    }

    public void setBtn_playlists(JButton btn_playlists) {
        this.btn_playlists = btn_playlists;
    }

    public JButton getBtn_sair() {
        return btn_sair;
    }

    public void setBtn_sair(JButton btn_sair) {
        this.btn_sair = btn_sair;
    }

    public JLabel getLbl_bem_vindo() {
        return lbl_bem_vindo;
    }

    public void setLbl_bem_vindo(JLabel lbl_bem_vindo) {
        this.lbl_bem_vindo = lbl_bem_vindo;
    }

    public JLabel getLbl_spotfei() {
        return lbl_spotfei;
    }

    public void setLbl_spotfei(JLabel lbl_spotfei) {
        this.lbl_spotfei = lbl_spotfei;
    }

    public JLabel getLbl_user() {
        return lbl_user;
    }

    public void setLbl_user(JLabel lbl_user) {
        this.lbl_user = lbl_user;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bem_vindo = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_spotfei = new javax.swing.JLabel();
        btn_playlists = new javax.swing.JButton();
        btn_musicas = new javax.swing.JButton();
        btn_history = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_bem_vindo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_bem_vindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bem_vindo.setText("Bem-Vindo,");

        lbl_user.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setText("Usuário");

        lbl_spotfei.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_spotfei.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_spotfei.setText("Spotfei");

        btn_playlists.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_playlists.setText("Gerenciar Playlists");
        btn_playlists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playlistsActionPerformed(evt);
            }
        });

        btn_musicas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_musicas.setText("Buscar Músicas");
        btn_musicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musicasActionPerformed(evt);
            }
        });

        btn_history.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_history.setText("Histórico");
        btn_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historyActionPerformed(evt);
            }
        });

        btn_sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sair.setText("SAIR");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_fechar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_fechar.setText("FECHAR");
        btn_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btn_playlists)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_bem_vindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_spotfei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btn_history, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_musicas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_fechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_spotfei)
                .addGap(27, 27, 27)
                .addComponent(lbl_bem_vindo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_user)
                .addGap(29, 29, 29)
                .addComponent(btn_playlists, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_musicas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_history, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_sair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_fechar)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playlistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playlistsActionPerformed
        // TODO add your handling code here:
        Playlists play = new Playlists();
        play.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_playlistsActionPerformed

    private void btn_musicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musicasActionPerformed
        // TODO add your handling code here:
        Buscar b = new Buscar();
        b.getLista_musicas().setFixedCellHeight(30);
        b.getLbl_info().setVisible(false);
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_musicasActionPerformed

    private void btn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historyActionPerformed
        // TODO add your handling code here:
        Historico h = new Historico();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_historyActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fecharActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Pagina_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Pagina_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Pagina_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pagina_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Pagina_Usuario().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_fechar;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_musicas;
    private javax.swing.JButton btn_playlists;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel lbl_bem_vindo;
    private javax.swing.JLabel lbl_spotfei;
    private javax.swing.JLabel lbl_user;
    // End of variables declaration//GEN-END:variables
}
