/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import control.ControllerMusica;

/**
 *
 * @author unifmkuniyoshi
 */
public class Musica_Info extends javax.swing.JFrame {

    /**
     * Creates new form Musica_Info
     */
    public Musica_Info() {
        initComponents();
        c = new ControllerMusica(null, this, null);
    }

    public JButton getBtn_salvar() {
        return btn_salvar;
    }

    public void setBtn_salvar(JButton btn_salvar) {
        this.btn_salvar = btn_salvar;
    }

    public JButton getBtn_voltar() {
        return btn_voltar;
    }

    public void setBtn_voltar(JButton btn_voltar) {
        this.btn_voltar = btn_voltar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLbl_musica_artista() {
        return lbl_musica_artista;
    }

    public void setLbl_musica_artista(JLabel lbl_musica_artista) {
        this.lbl_musica_artista = lbl_musica_artista;
    }

    public JLabel getLbl_musica_genero() {
        return lbl_musica_genero;
    }

    public void setLbl_musica_genero(JLabel lbl_musica_genero) {
        this.lbl_musica_genero = lbl_musica_genero;
    }

    public JLabel getLbl_musica_nome() {
        return lbl_musica_nome;
    }

    public void setLbl_musica_nome(JLabel lbl_musica_nome) {
        this.lbl_musica_nome = lbl_musica_nome;
    }

    public JLabel getLbl_playlist() {
        return lbl_playlist;
    }

    public void setLbl_playlist(JLabel lbl_playlist) {
        this.lbl_playlist = lbl_playlist;
    }

    public JList<String> getLista_playlists() {
        return lista_playlists;
    }

    public void setLista_playlists(JList<String> lista_playlists) {
        this.lista_playlists = lista_playlists;
    }

    public JButton getBtn_dislike() {
        return btn_dislike;
    }

    public void setBtn_dislike(JButton btn_dislike) {
        this.btn_dislike = btn_dislike;
    }

    public JButton getBtn_like() {
        return btn_like;
    }

    public void setBtn_like(JButton btn_like) {
        this.btn_like = btn_like;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_musica_nome = new javax.swing.JLabel();
        lbl_musica_artista = new javax.swing.JLabel();
        lbl_musica_genero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_playlists = new javax.swing.JList<>();
        lbl_playlist = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_like = new javax.swing.JButton();
        btn_dislike = new javax.swing.JButton();
        lbl_musica_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_musica_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica_nome.setText("Nome da Música");

        lbl_musica_artista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica_artista.setText("Artista");

        lbl_musica_genero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica_genero.setText("Gênero");

        lista_playlists.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista_playlists);

        lbl_playlist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_playlist.setText("Selecione a Playlist:");

        btn_voltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_salvar.setText("Adicionar à Playlist");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_like.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_like.setText("Curtir");
        btn_like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_likeActionPerformed(evt);
            }
        });

        btn_dislike.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dislike.setText("Descurtir");
        btn_dislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dislikeActionPerformed(evt);
            }
        });

        lbl_musica_info.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_musica_info.setText("Nome da Música, Artista e Gênero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_voltar)
                                    .addComponent(lbl_playlist)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_musica_nome)
                                        .addGap(38, 38, 38)
                                        .addComponent(lbl_musica_artista)
                                        .addGap(41, 41, 41)
                                        .addComponent(lbl_musica_genero)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(btn_salvar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_like)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_dislike)))
                        .addGap(0, 144, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_musica_info)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lbl_musica_info)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_musica_nome)
                    .addComponent(lbl_musica_artista)
                    .addComponent(lbl_musica_genero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_like)
                    .addComponent(btn_dislike))
                .addGap(18, 18, 18)
                .addComponent(lbl_playlist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_salvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        c.salvarMusica(this);
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_likeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_likeActionPerformed
        // TODO add your handling code here:
        c.curtir(lbl_musica_nome);
    }//GEN-LAST:event_btn_likeActionPerformed

    private void btn_dislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dislikeActionPerformed
        // TODO add your handling code here:
        c.descurtir(lbl_musica_nome);
    }//GEN-LAST:event_btn_dislikeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Musica_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Musica_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Musica_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Musica_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Musica_Info().setVisible(true);
//            }
//        });
//    }
    private ControllerMusica c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dislike;
    private javax.swing.JButton btn_like;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_musica_artista;
    private javax.swing.JLabel lbl_musica_genero;
    private javax.swing.JLabel lbl_musica_info;
    private javax.swing.JLabel lbl_musica_nome;
    private javax.swing.JLabel lbl_playlist;
    private javax.swing.JList<String> lista_playlists;
    // End of variables declaration//GEN-END:variables
}
