/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ControllerPlaylists;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifmkuniyoshi
 */
public class Playlists_Criar extends javax.swing.JFrame {

    /**
     * Creates new form Playlists_Criar
     */
    public Playlists_Criar() {
        initComponents();
        
        c = new ControllerPlaylists(this);
    }

    public JButton getBtn_playlist_cancelar() {
        return btn_playlist_cancelar;
    }

    public void setBtn_playlist_cancelar(JButton btn_playlist_cancelar) {
        this.btn_playlist_cancelar = btn_playlist_cancelar;
    }

    public JButton getBtn_playlist_criar() {
        return btn_playlist_criar;
    }

    public void setBtn_playlist_criar(JButton btn_playlist_criar) {
        this.btn_playlist_criar = btn_playlist_criar;
    }

    public JLabel getLbl_playlist_criar() {
        return lbl_playlist_criar;
    }

    public void setLbl_playlist_criar(JLabel lbl_playlist_criar) {
        this.lbl_playlist_criar = lbl_playlist_criar;
    }

    public JLabel getLbl_playlist_nome() {
        return lbl_playlist_nome;
    }

    public void setLbl_playlist_nome(JLabel lbl_playlist_nome) {
        this.lbl_playlist_nome = lbl_playlist_nome;
    }

    public JTextField getTxt_playlist_nome() {
        return txt_playlist_nome;
    }

    public void setTxt_playlist_nome(JTextField txt_playlist_nome) {
        this.txt_playlist_nome = txt_playlist_nome;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_playlist_criar = new javax.swing.JLabel();
        txt_playlist_nome = new javax.swing.JTextField();
        btn_playlist_criar = new javax.swing.JButton();
        btn_playlist_cancelar = new javax.swing.JButton();
        lbl_playlist_nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_playlist_criar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_playlist_criar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_playlist_criar.setText("Criar Playlist");

        btn_playlist_criar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_playlist_criar.setText("Criar");
        btn_playlist_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playlist_criarActionPerformed(evt);
            }
        });

        btn_playlist_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_playlist_cancelar.setText("Cancelar");
        btn_playlist_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playlist_cancelarActionPerformed(evt);
            }
        });

        lbl_playlist_nome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_playlist_nome.setText("Nome da Playlist:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_playlist_criar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_playlist_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_playlist_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_playlist_cancelar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btn_playlist_criar)))
                .addGap(193, 193, 193))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_playlist_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_playlist_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_playlist_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_playlist_criar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_playlist_cancelar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playlist_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playlist_criarActionPerformed
        // TODO add your handling code here:
        c.salvarPlaylist();
        txt_playlist_nome.setText("");
    }//GEN-LAST:event_btn_playlist_criarActionPerformed

    private void btn_playlist_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playlist_cancelarActionPerformed
        // TODO add your handling code here:
        Playlists p = new Playlists();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_playlist_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Playlists_Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Playlists_Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Playlists_Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Playlists_Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Playlists_Criar().setVisible(true);
//            }
//        });
//    }
    
    private ControllerPlaylists c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_playlist_cancelar;
    private javax.swing.JButton btn_playlist_criar;
    private javax.swing.JLabel lbl_playlist_criar;
    private javax.swing.JLabel lbl_playlist_nome;
    private javax.swing.JTextField txt_playlist_nome;
    // End of variables declaration//GEN-END:variables
}
