/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import control.ControllerPlaylists;
import javax.swing.JFrame;

/**
 *
 * @author Yudi
 */
public class Playlists_Ver extends javax.swing.JFrame {

    /**
     * Creates new form Musica_Deletar
     */
    public Playlists_Ver(JFrame janelaOriginal) {
        initComponents();
        this.janelaOriginal = janelaOriginal;
        c = new ControllerPlaylists(null, null, null, null, this);
    }

    public JButton getBtn_voltar() {
        return btn_voltar;
    }

    public void setBtn_voltar(JButton btn_voltar) {
        this.btn_voltar = btn_voltar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLbl_select() {
        return lbl_select;
    }

    public void setLbl_select(JLabel lbl_select) {
        this.lbl_select = lbl_select;
    }

    public JLabel getLbl_titulo() {
        return lbl_titulo;
    }

    public void setLbl_titulo(JLabel lbl_titulo) {
        this.lbl_titulo = lbl_titulo;
    }

    public JList<String> getLista_playlists() {
        return lista_playlists;
    }

    public void setLista_playlists(JList<String> lista_playlists) {
        this.lista_playlists = lista_playlists;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_playlists = new javax.swing.JList<>();
        lbl_select = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_titulo.setText("Suas Playlists");

        lista_playlists.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_playlists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_playlistsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista_playlists);

        lbl_select.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_select.setText("Clique duas vezes para abrir a playlist:");

        btn_voltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_voltar)
                                .addGap(56, 56, 56)
                                .addComponent(lbl_titulo))
                            .addComponent(lbl_select))
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_titulo)
                    .addComponent(btn_voltar))
                .addGap(18, 18, 18)
                .addComponent(lbl_select)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void lista_playlistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_playlistsMouseClicked
        // TODO add your handling code here:
        Playlist_Info pi = new Playlist_Info();
        if(evt.getClickCount() == 2){
            pi.getLista_musicas().setFixedCellHeight(30);
            int vazia = c.mostarMusicasPlaylist(pi.getLista_musicas());
            if(vazia != 1){
            pi.getLbl_nome().setText("Nome da Playlist: " 
                + lista_playlists.getSelectedValue());
            if(janelaOriginal instanceof Playlists){
                pi.getBtn_delete().setVisible(false);
                pi.getLbl_select().setText("Músicas:");
            }
            pi.setVisible(true);
            }
        }
    }//GEN-LAST:event_lista_playlistsMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Playlists_Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Playlists_Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Playlists_Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Playlists_Ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Playlists_Ver().setVisible(true);
//            }
//        });
//    }
    private JFrame janelaOriginal;
    private ControllerPlaylists c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_select;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JList<String> lista_playlists;
    // End of variables declaration//GEN-END:variables
}
